Fixed error fetching special feeds
A String with the class name was being used instead of the actual
handler class. This raised an error:  NoMethodError: undefined method `fetch_feed' for "TumblrFeedFetcher":String