Pinned rest-client version to 1.8.0
It seems rest-client-components, which is used to add client-side caching through rack-cache, is imcompatible with version 2 of rest-client. I get errors like this:

NoMethodError: undefined method `redirection_history' for {}:Hash
…/rest-client-2.0.0/lib/restclient/
abstract_response.rb:  20:in `history'
…/rest-client-2.0.0/lib/restclient/
abstract_response.rb:  39:in `response_set_vars'
….3.0/gems/rest-client-2.0.0/lib/restclient/
/var/rails/feedbunch/shared/bundle/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient/response.rb
response.rb:  44:in `create'
…t-client-components-1.4.0/lib/restclient/
components.rb:  18:in `call'
…t-client-components-1.4.0/lib/restclient/components.rb: 139:in `execute'
…/rest-client-2.0.0/lib/restclient/abstract_response.rb: 207:in `_follow_redirection'
…/rest-client-2.0.0/lib/restclient/abstract_response.rb: 119:in `follow_redirection'
…/rest-client-2.0.0/lib/restclient/abstract_response.rb:  95:in `return!'
…2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb: 860:in `process_result'
…2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb: 776:in `block in transmit'
…unch/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb: 853:in `start'
…2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb: 766:in `transmit'
…2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb: 215:in `execute'
…t-client-components-1.4.0/lib/restclient/components.rb: 206:in `block in <module:RestClient>'
…/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb: 140:in `forward'
…/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb: 249:in `fetch'
…/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb: 189:in `lookup'
…/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:  66:in `call!'
…/2.3.0/gems/rack-cache-1.6.1/lib/rack/cache/
context.rb:  51:in `call'
…t-client-components-1.4.0/lib/restclient/
components.rb:  12:in `call'
…t-client-components-1.4.0/lib/restclient/
components.rb: 139:in `execute'
…2.3.0/gems/rest-client-2.0.0/lib/restclient/
request.rb:  52:in `execute'
…le/ruby/2.3.0/gems/rest-client-2.0.0/lib/restclient.rb:  67:in `get'
…nch/releases/20160722142151/app/clients/feed_client.rb: 105:in `fetch_valid_feed'